### PR TITLE
Vendor our dependencies with `vgo`

### PR DESCRIPTION
**Pull request by karlek**
Result from `vgo test all`:

```
ok  	azul3d.org/engine/audio	(cached)
--- FAIL: TestDecodeFloat32 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeFloat64 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeUInt8 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt16 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt24 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt32 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeALaw (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeMuLaw (0.00s)
	decode_test.go:34: audio: unknown format
FAIL
FAIL	azul3d.org/engine/audio/wav	0.371s
ok  	github.com/djimenez/iconv-go	(cached)
ok  	github.com/icza/bitio	(cached)
ok  	github.com/icza/mighty	(cached)
ok  	github.com/mewkiz/flac	(cached)
?   	github.com/mewkiz/flac/cmd/flac2wav	[no test files]
?   	github.com/mewkiz/flac/cmd/go-metaflac	[no test files]
ok  	github.com/mewkiz/flac/frame	(cached)
ok  	github.com/mewkiz/flac/internal/bits	(cached)
?   	github.com/mewkiz/flac/internal/hashutil	[no test files]
ok  	github.com/mewkiz/flac/internal/hashutil/crc16	(cached)
ok  	github.com/mewkiz/flac/internal/hashutil/crc8	(cached)
ok  	github.com/mewkiz/flac/meta	(cached)
ok  	github.com/mewkiz/pkg/errutil	(cached)
?   	github.com/mewkiz/pkg/osutil	[no test files]
?   	github.com/mewkiz/pkg/pathutil	[no test files]
?   	github.com/mewkiz/pkg/term	[no test files]
ok  	github.com/mikkyang/id3-go/encodedbytes	(cached)
```

### CODE REVIEW

**Comment by mewmew** [comment]
Hmm. Try `vgo test all -count=1` to re-run cached test cases.

**Comment by karlek** [comment]
Same result: 

```
ok  	azul3d.org/engine/audio	0.007s
--- FAIL: TestDecodeFloat32 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeFloat64 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeUInt8 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt16 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt24 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeInt32 (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeALaw (0.00s)
	decode_test.go:34: audio: unknown format
--- FAIL: TestDecodeMuLaw (0.00s)
	decode_test.go:34: audio: unknown format
FAIL
FAIL	azul3d.org/engine/audio/wav	0.348s
ok  	github.com/djimenez/iconv-go	0.005s
ok  	github.com/icza/bitio	0.080s
ok  	github.com/icza/mighty	0.011s
ok  	github.com/mewkiz/flac	0.064s
?   	github.com/mewkiz/flac/cmd/flac2wav	[no test files]
?   	github.com/mewkiz/flac/cmd/go-metaflac	[no test files]
ok  	github.com/mewkiz/flac/frame	1.273s
ok  	github.com/mewkiz/flac/internal/bits	0.009s
?   	github.com/mewkiz/flac/internal/hashutil	[no test files]
ok  	github.com/mewkiz/flac/internal/hashutil/crc16	0.002s
ok  	github.com/mewkiz/flac/internal/hashutil/crc8	0.010s
ok  	github.com/mewkiz/flac/meta	0.010s
ok  	github.com/mewkiz/pkg/errutil	0.007s
?   	github.com/mewkiz/pkg/osutil	[no test files]
?   	github.com/mewkiz/pkg/pathutil	[no test files]
?   	github.com/mewkiz/pkg/term	[no test files]
ok  	github.com/mikkyang/id3-go/encodedbytes	0.006s
```

**Comment by mewmew** [comment]
Does not seem like vgo is working with lfs:

```
u@x220 ~/D/g/s/g/m/flac> vgo build ./...
vgo: creating new go.mod: module github.com/mewkiz/flac
vgo: resolving import "github.com/icza/bitio"
vgo: finding github.com/icza/bitio (latest)
vgo: adding github.com/icza/bitio v0.0.0-20180221120200-b25b30b42508
vgo: resolving import "github.com/mewkiz/pkg/errutil"
vgo: finding github.com/mewkiz/pkg (latest)
vgo: adding github.com/mewkiz/pkg v0.0.0-20170428133157-c19a6f9fa6f8
vgo: resolving import "github.com/mikkyang/id3-go/encodedbytes"
vgo: finding github.com/mikkyang/id3-go (latest)
vgo: adding github.com/mikkyang/id3-go v0.0.0-20151201011346-0168d962f1d7
vgo: resolving import "azul3d.org/engine/audio"
vgo: finding azul3d.org/engine (latest)
vgo: adding azul3d.org/engine v0.0.0-20170701203912-eb48fbeb6d97
vgo: finding azul3d.org/engine v0.0.0-20170701203912-eb48fbeb6d97
vgo: finding github.com/mikkyang/id3-go v0.0.0-20151201011346-0168d962f1d7
vgo: finding github.com/mewkiz/pkg v0.0.0-20170428133157-c19a6f9fa6f8
vgo: finding github.com/icza/bitio v0.0.0-20180221120200-b25b30b42508
vgo: downloading github.com/icza/bitio v0.0.0-20180221120200-b25b30b42508
vgo: downloading github.com/mewkiz/pkg v0.0.0-20170428133157-c19a6f9fa6f8
vgo: downloading github.com/mikkyang/id3-go v0.0.0-20151201011346-0168d962f1d7
vgo: downloading azul3d.org/engine v0.0.0-20170701203912-eb48fbeb6d97
vgo: import "github.com/mewkiz/flac/cmd/flac2wav" ->
	import "azul3d.org/engine/audio": git archive --format=zip --prefix=prefix/ eb48fbeb6d97ddebb823269e5cf41ae0af903765 in /home/u/goget/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c: exit status 128:
	Downloading audio/flac/testdata/tune_stereo_44100hz_int16.flac (78.33 KB)
	Error downloading object: audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e)
	
	Errors logged to /home/u/goget/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/objects/logs/20180528T094218.71498126.log
	Use `git lfs logs last` to view the log.
	error: external filter 'git-lfs filter-process' failed
	fatal: audio/flac/testdata/tune_stereo_44100hz_int16.flac: smudge filter lfs failed
vgo: downloading azul3d.org/engine v0.0.0-20170701203912-eb48fbeb6d97
vgo: import "github.com/mewkiz/flac/cmd/flac2wav" ->
	import "azul3d.org/engine/audio/wav": git archive --format=zip --prefix=prefix/ eb48fbeb6d97ddebb823269e5cf41ae0af903765 in /home/u/goget/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c: exit status 128:
	Downloading audio/flac/testdata/tune_stereo_44100hz_int16.flac (78.33 KB)
	Error downloading object: audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e)
	
	Errors logged to /home/u/goget/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/objects/logs/20180528T094219.271448314.log
	Use `git lfs logs last` to view the log.
	error: external filter 'git-lfs filter-process' failed
	fatal: audio/flac/testdata/tune_stereo_44100hz_int16.flac: smudge filter lfs failed
vgo: resolving import "github.com/djimenez/iconv-go"
vgo: finding github.com/djimenez/iconv-go (latest)
vgo: adding github.com/djimenez/iconv-go v0.0.0-20160305225143-8960e66bd3da
```

**Comment by karlek** [comment]
Couldn't find any issues (open nor closed) about problems with lfs:
https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+x%2Fvgo+lfs

What does the log say?

**Comment by mewmew** [comment]
```
[u@x220 flac]$ git lfs logs last
No logs to show
```

**Comment by karlek** [comment]
Are the files empty?
```
$ cat /home/u/goget/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/objects/logs/20180528T094219.271448314.log
```

**Comment by mewmew** [comment]
```
u@x220 /t/g/s/v/c/v/3/l/o/logs> cat *
git-lfs/2.0.0 (GitHub; linux amd64; go devel +438a757d73 Wed Feb 21 18:10:00 2018 +0000)
git version 2.17.0

$ git-lfs filter-process
Error downloading object: audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e)

Smudge error: Error downloading audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e): batch response: Post /objects/batch: unsupported protocol scheme ""
github.com/git-lfs/git-lfs/errors.newWrappedError
	/home/u/goget/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	/home/u/goget/src/github.com/git-lfs/git-lfs/errors/types.go:252
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:68
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:63
github.com/git-lfs/git-lfs/commands.filterCommand
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	/home/u/goget/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	/home/u/goget/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	/home/u/goget/src/github.com/github/git-lfs/git-lfs.go:35
runtime.main
	/home/u/go/src/runtime/proc.go:198
runtime.goexit
	/home/u/go/src/runtime/asm_amd64.s:2361

ENV:
LocalWorkingDir=
LocalGitDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c
LocalGitStorageDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c
LocalMediaDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/objects
LocalReferenceDir=
TempDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.
GIT_PREFIX=
GIT_IMPLICIT_WORK_TREE=0
git-lfs/2.0.0 (GitHub; linux amd64; go devel +438a757d73 Wed Feb 21 18:10:00 2018 +0000)
git version 2.17.0

$ git-lfs filter-process
Error downloading object: audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e)

Smudge error: Error downloading audio/flac/testdata/tune_stereo_44100hz_int16.flac (2091f011ecd9a3af0a56a6f5a14ae7e5ffb95158b8316b7cb534dbe43b9b152e): batch response: Post /objects/batch: unsupported protocol scheme ""
github.com/git-lfs/git-lfs/errors.newWrappedError
	/home/u/goget/src/github.com/git-lfs/git-lfs/errors/types.go:166
github.com/git-lfs/git-lfs/errors.NewSmudgeError
	/home/u/goget/src/github.com/git-lfs/git-lfs/errors/types.go:252
github.com/git-lfs/git-lfs/lfs.PointerSmudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/lfs/pointer_smudge.go:68
github.com/git-lfs/git-lfs/lfs.(*Pointer).Smudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/lfs/pointer.go:64
github.com/git-lfs/git-lfs/commands.smudge
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/command_smudge.go:63
github.com/git-lfs/git-lfs/commands.filterCommand
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:65
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute
	/home/u/goget/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute
	/home/u/goget/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551
github.com/git-lfs/git-lfs/commands.Run
	/home/u/goget/src/github.com/git-lfs/git-lfs/commands/run.go:68
main.main
	/home/u/goget/src/github.com/github/git-lfs/git-lfs.go:35
runtime.main
	/home/u/go/src/runtime/proc.go:198
runtime.goexit
	/home/u/go/src/runtime/asm_amd64.s:2361

ENV:
LocalWorkingDir=
LocalGitDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c
LocalGitStorageDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c
LocalMediaDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/objects
LocalReferenceDir=
TempDir=/tmp/go/src/v/cache/vcswork/33d7fd8670cc26328c70a1aa2e256f39e8677b5051ce504802f38deaa8cce53c/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_DIR=.
GIT_PREFIX=
GIT_IMPLICIT_WORK_TREE=0
```

**Comment by mewmew** [comment]
Good that you actually read the error message, I only skim it to look for *next course of action* :)

**Comment by mewmew** [comment]
Reported upstream at golang/go#25605. Haha, this morning has been a bug hunt all over the place.

**Comment by karlek** [comment]
Haha yeah, and very few are in our repo 😎

**Comment by mewmew** [comment]
The upstream issue has been fixed. Merging :)

**Pull request merged**
