### PR TITLE
Feature - Add cli, fix test case

### PR DESCRIPTION
**Pull request by fwx5618177**
Feature:
1. Add CLI main.go
2. Fix up test cases
3. Move test data to one integration directory.
4. Add usage info.

image

### CODE REVIEW

**Comment by fwx5618177** [comment]
@chewxy @cswank @karlek @mewmew PTAL.

**Comment by karlek** [comment]
Hi @fwx5618177!

Cool that you have found our flac library (and thanks for contributing!). I'm meeting @mewmew later tonight, so we'll take a look then.

Cheers Henry & Robin

**Comment by mewmew** [comment]
Hi @fwx5618177,

My brother and I are glad that you feel you want to contribute to the flac library.

After some considerations, we've decided to not merge this PR.

The `mewkiz/flac` repository is primarily used as a library to decode FLAC audio files. The tools within the `cmd/` directory are mainly to be seen as examples for how the library may be used.

That being said, adding an abstraction with subcommands feels like the wrong direction to move in, since then the examples become coupled to one another and it also puts emphasis that these tools are how you're supposed to use the `flac` repo. They are not, they are really only meant to be used as *code examples*.

So, while we think it's good that you feel you want to contribute to the project, we would rather keep the `cmd/` examples as simple as possible and also keep the readme in its current state, to put emphasis that the `mewkiz/flac` repo is to be used as a library, and that the tools themselves are not really meant as end-user tools. Just as code examples.

Thus, we'll close this PR.

Wish you all the best and happy coding,
Henry & Robin

**Comment by fwx5618177** [comment]
> Hi @fwx5618177,
> 
> My brother and I are glad that you feel you want to contribute to the flac library.
> 
> After some considerations, we've decided to not merge this PR.
> 
> The `mewkiz/flac` repository is primarily used as a library to decode FLAC audio files. The tools within the `cmd/` directory are mainly to be seen as examples for how the library may be used.
> 
> That being said, adding an abstraction with subcommands feels like the wrong direction to move in, since then the examples become coupled to one another and it also puts emphasis that these tools are how you're supposed to use the `flac` repo. They are not, they are really only meant to be used as _code examples_.
> 
> So, while we think it's good that you feel you want to contribute to the project, we would rather keep the `cmd/` examples as simple as possible and also keep the readme in its current state, to put emphasis that the `mewkiz/flac` repo is to be used as a library, and that the tools themselves are not really meant as end-user tools. Just as code examples.
> 
> Thus, we'll close this PR.
> 
> Wish you all the best and happy coding, Henry & Robin

I got your mean. It needs to be as a lib to use.

**Comment by mewmew** [comment]
> I got your mean. It needs to be as a lib to use.

Glad to hear.

Cheers,
Robin

**Pull request closed without merging**
